### ISSUE TITLE
Lp2go device restrictions / cannot install on FireOS tablet

### ISSUE THREAD

**Issue by cjander** [MarcProe/lp2go#20]
Hi guy's,

I just joined the test today and directly headed into a minor issue. When trying to download the app via the AppStore, Google did not allowed the installation on my android tablet ( play store tells me it's only for phones). I can of cause compile it by myself, but why the restriction at all?

**Comment by MarcProe** [comment]
I am looking into this at the moment. It seems that the playstore has some problems with allowing some tablets.

As a workaround you can download the latest alpha APK at https://github.com/MarcProe/lp2go/blob/master/app/app-alpha_flavor_-release.apk

However, this has to be updated "by hand" frequently.

**Comment by MarcProe** [comment]
could be possible that your tablet does not support usb otg.
I set `required` for this to false

```
   <uses-feature
        android:name="android.hardware.usb.host"
        android:required="false" />

```

It will take a few hours for this to go to the playstore, cann you test tomorrow evening?

**Comment by MarcProe** [comment]
![image](https://cloud.githubusercontent.com/assets/11455452/13731573/b2b5f8ca-e96c-11e5-954d-2406c45f7bf9.png)

Looks like this _might_ be it

**Comment by cjander** [comment]
I'm using an Amazon Fire HD8, and I used otg on this already. let's see, booting up my old Nexus now

**Comment by MarcProe** [comment]
New version is live in the playstore, please try again.

**Comment by cjander** [comment]
Same as before. Will try the nexus  (Manual installation via apg works of cause)
Edit: nexus works fine...

**Comment by MarcProe** [comment]
What android version do you have installed on the fire?

**Comment by cjander** [comment]
They call it Fire OS 5.1.1, I'm not sure which version of android they've used, I just know it's  lollipop

**Comment by MarcProe** [comment]
I can only assume that there are issues with the playstore. On FireOS, it is not installed by default, you have to do some quirky stuff to get it running.  I have a Fire 7 here and will try later if I have the same issue.

**Comment by MarcProe** [comment]
Please try again tonight. [Fire HD8](http://www.gsmarena.com/amazon_fire_hd_8-7610.php) has no GPS, that could've been the problem.
![image](https://cloud.githubusercontent.com/assets/11455452/13769647/9d3c74ea-ea81-11e5-82f7-e594c58eccb8.png)

**Comment by MarcProe** [comment]
@cjander, may I ask if you now can install via the playstore? Thanks a lot for being so helpful with this issue.

**Comment by cjander** [comment]
Ah sorry totally forgot to post. No it's still the same, amazon fire doesn't work, nexus 7 does.

**Comment by MarcProe** [comment]
Thanks for the info. Well, I am out of ideas unfortunately. I guess for the moment we'll have to live with that, until I have a flash of inspiration... Thanks for your help!

**Comment by MarcProe** [comment]
Curren Beta APK: https://github.com/MarcProe/lp2go/blob/branch_public_beta_0.3/app/app-beta_flavor_-release.apk

**Comment by MarcProe** [comment]
LibrePilot2Go can now be downloaded at the Amazon App Store.:
http://www.amazon.com/gp/mas/dl/android?p=org.librepilot.lp2go.beta
