### ISSUE TITLE
Capacity + Cells tile

### ISSUE THREAD

**Issue by cjander** [MarcProe/lp2go#25]
A: I can set values for Capacity & Cells, but the value is not visible after i've set them.

B:  in the edit window there are buttons for "update", "cancel" and "save". 
Where is the difference between "update" & "save"?

**Comment by MarcProe** [comment]
A: Yes, this should be only possible if a Current and Voltage Sensor is installed (https://librepilot.atlassian.net/wiki/display/LPDOC/Configure+a+Current-Voltage+sensor).
B: "Update/Upload" transmits the data to the FC and uses the new settings, but does not save persistent, so the data is lost after reboot. "Save" saves persistent, so the data is still there after reboot. Will update wiki.
