### ISSUE TITLE
Altitude Hold VerticalVelPID + VericalPosP

### ISSUE THREAD

**Issue by mashu** [MarcProe/lp2go#28]
Would be really nice to be able to set those from LP2Go
- VerticalVelPID (Kp, Ki, Kd, Beta)
- VerticalPosP
- ThrustRate
- ThrustExp

**Comment by MarcProe** [comment]
![image](https://cloud.githubusercontent.com/assets/11455452/14519405/f660069a-021e-11e6-808f-acff6c9a8d7e.png)
