### ISSUE TITLE
Latitude not correctly shown in OpMap

### ISSUE THREAD

**Issue by jferfre** [MarcProe/lp2go#32]
Oplink connected to a OnePlusOne (CyanoGenMod Android 5), through  OTG Cable. Revolution with integrated modem. 
3min to get Fix 3D with more than 10 sats.  
- In Ip2Go, longitude is +425.52, but really is -3.97. Disconnected OTG Cable, connected (without turning off the aircraft) the GCS in Windows (same OpLink ground modem)
  and correct coordinates shown. 

![clipboard01](https://cloud.githubusercontent.com/assets/18451521/14543115/eefa7844-0292-11e6-9458-312b699445b9.jpg)
![screenshot_2016-04-14-19-09-17](https://cloud.githubusercontent.com/assets/18451521/14543114/eef9520c-0292-11e6-92c2-abc1677a82da.png)
![screenshot_2016-04-14-19-10-08](https://cloud.githubusercontent.com/assets/18451521/14543113/eef88d72-0292-11e6-8c5d-678e95abbb17.png)

Just let me know any additional information needed

**Comment by MarcProe** [comment]
additional user report: 
![image](https://cloud.githubusercontent.com/assets/11455452/14580409/f77c1bb4-03cb-11e6-8721-457cd978dfd8.png)

**Comment by jferfre** [comment]
Hi. 
Solved in 0.2.5.27.
Thanks
^_Pepe_^

**Comment by MarcProe** [comment]
Fixed in fd474d93, thanks for feedback!
