### ISSUE TITLE
Send waypoint UAVO

### ISSUE THREAD

**Issue by gonsp** [MarcProe/lp2go#39]
Hi,

I'm trying to write a computer program which needs to send different waypoints. I'm using your library but I'm stuck sending the waypoints. (I've been able to send some other things like the HomePosition)

This is the code I'm using to send them:
```
    private void upload(FcDevice device, Waypoint waypoint, int id) {
        byte data[] = new byte[device.getObjectTree().getXmlObjects().get("Waypoint").getLength()];
        //Adding the new instance
        UAVTalkObjectInstance instance = new UAVTalkObjectInstance(id, data);
        UAVTalkObject waypoints = device.getObjectTree().getObjectFromName("Waypoint");
        waypoints.setInstance(instance);

        //Setting the position of the new instance
        sendField(device, id, "Position", 0, waypoint.lat);
        sendField(device, id, "Position", 1, waypoint.lng);
        sendField(device, id, "Position", 2, -waypoint.alt);
        sendField(device, id, "Velocity", 0, waypoint.velocity);
    }

    private void sendField(FcDevice device, int instanceID, String fieldName, int elementID, double value) {
        byte fieldData[] = ByteBuffer.allocate(4).putFloat((float) value).array();
        device.sendSettingsObject("Waypoint", instanceID, fieldName, elementID, fieldData);
    }
```
What am I doing wrong? I'm receiving the ACK for each field but I see no change after sending them. Is it because the UAVO is not a "settings" one?

PD: I'm calling the "upload" method with id = 0 and id = 1.

Would love any help!

**Comment by gonsp** [comment]
Okay, I wasn't uploading correctly the PathPlan CRC. It's working great now!

**Comment by MarcProe** [comment]
Sorry, wasn't monitoring this closely the last few months. Great that it works!
